### ISSUE TITLE
Problem when moving the starting/ending square

### ISSUE THREAD

**Issue by Arthaudcom** [ClementDrn/Pathfinding#2] opened 2022-03-10 03:39 UTC
When I build a wall somewhere on the map and then move one of the squares, the path doesn't recognize walls and just go through it.

![image](https://user-images.githubusercontent.com/85752922/157583838-d4b726f0-a616-4c14-a597-694b8da0ec47.png)

![image](https://user-images.githubusercontent.com/85752922/157583785-40858a47-ab05-4378-ae40-43028d36d858.png)

**Comment by ClementDrn** [comment] 2022-03-11 05:00
Thank you for reporting this bug. I think this problems occurs because when moving starting/ending points, obtacles are deleted if the mouse touch them,  but there are not updated on the window.

**Comment by ClementDrn** [comment] 2022-03-11 05:45
The issue is fixed in release v2.0.1.

**Closed as completed by ClementDrn** 2022-03-11 05:45 UTC
Labels: bug
